name: hashtag Recruitment
favicon: null
layout_spectrum: 0.01434
typography_spectrum: 0.46815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffefd'
    - '#eb692d'
    - '#181717'
    - '#f7bea0'
    - '#5b5b5b'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.39161188807338476
  rhythmicContrast: 0.25
purpose: []
