name: hashtag Recruitment
favicon: null
layout_spectrum: 0.01434
typography_spectrum: 0.46815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff6e01'
    - '#d1d1d1'
    - '#131311'
    - '#7d7d7d'
  brandStrength: 0.36377401230856776
  lightness: 0.20277511212043464
  saturation: 0.39161188807338476
  rhythmicContrast: 0.7918982314877212
purpose: []
